package Visao;

import Controle.ControlaVenda;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.ItemVenda;
import modelo.ItemVendaPK;

import modelo.Produto;
import modelo.Venda;

/**
 *
 * @author Luan
 */
public class TelaVenda extends javax.swing.JInternalFrame {

    boolean novo;
    int alterarC;
    ControlaVenda controle = new ControlaVenda(Entidades.GerenciamentoEntidades.getFabEntidades());

    Produto prodSelecionado;

    public TelaVenda() {
        initComponents();
        panGuia.setEnabledAt(0, true);
        panGuia.setEnabledAt(1, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        Luan_ProjetoPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("Luan_ProjetoPU").createEntityManager();
        vendaQuery = java.beans.Beans.isDesignTime() ? null : Luan_ProjetoPUEntityManager.createQuery("SELECT v FROM Venda v");
        vendaList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(vendaQuery.getResultList());
        listItemVenda = org.jdesktop.observablecollections.ObservableCollections.observableList(new ArrayList<ItemVenda>());
        panGuia = new javax.swing.JTabbedPane();
        panOp = new javax.swing.JPanel();
        panAction = new javax.swing.JPanel();
        botNovo = new javax.swing.JButton();
        botAlterar = new javax.swing.JButton();
        botExcluir = new javax.swing.JButton();
        botSair = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabVenda = new javax.swing.JTable();
        botPesquisar = new javax.swing.JButton();
        panDados = new javax.swing.JPanel();
        botCancelar = new javax.swing.JButton();
        Salvar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabProduto = new javax.swing.JTable();
        panProduto = new javax.swing.JPanel();
        labValor = new javax.swing.JLabel();
        labProduto = new javax.swing.JLabel();
        labEstoque = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        botDialog = new javax.swing.JButton();
        botAdicionarProd = new javax.swing.JButton();
        botExcluirProd = new javax.swing.JButton();
        labQuantidade = new javax.swing.JLabel();
        txtValorProduto = new javax.swing.JFormattedTextField();
        txtEstoque = new javax.swing.JFormattedTextField();
        txtQuant = new javax.swing.JFormattedTextField();
        panVenda = new javax.swing.JPanel();
        txtCodVenda = new javax.swing.JTextField();
        labCondigoVenda = new javax.swing.JLabel();
        txtDesconto = new javax.swing.JFormattedTextField();
        labDesconto = new javax.swing.JLabel();
        txtValor = new javax.swing.JFormattedTextField();
        labValorVenda = new javax.swing.JLabel();
        labValorVenda1 = new javax.swing.JLabel();
        Data = new com.toedter.calendar.JDateChooser();

        panGuia.setName("Cliente"); // NOI18N

        panAction.setBorder(javax.swing.BorderFactory.createTitledBorder("Ações"));
        panAction.setLayout(new java.awt.GridLayout(1, 0));

        botNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/Imagens/icons8-Mais-30.png"))); // NOI18N
        botNovo.setText("Novo");
        botNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botNovoActionPerformed(evt);
            }
        });
        panAction.add(botNovo);

        botAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/Imagens/Editar-30.png"))); // NOI18N
        botAlterar.setText("Alterar");
        botAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAlterarActionPerformed(evt);
            }
        });
        panAction.add(botAlterar);

        botExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/Imagens/Excluir-30.png"))); // NOI18N
        botExcluir.setText("Excluir");
        botExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botExcluirActionPerformed(evt);
            }
        });
        panAction.add(botExcluir);

        botSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/Imagens/Porta aberta-30.png"))); // NOI18N
        botSair.setText("Sair");
        botSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botSairActionPerformed(evt);
            }
        });
        panAction.add(botSair);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar Vendas"));

        jLabel1.setText("Codigo Da Venda");

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, vendaList, tabVenda);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${desconto}"));
        columnBinding.setColumnName("Desconto");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${valor}"));
        columnBinding.setColumnName("Valor");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codVenda}"));
        columnBinding.setColumnName("Cod Venda");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(tabVenda);

        botPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/Imagens/Pesquisar-15.png"))); // NOI18N
        botPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(botPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout panOpLayout = new javax.swing.GroupLayout(panOp);
        panOp.setLayout(panOpLayout);
        panOpLayout.setHorizontalGroup(
            panOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panOpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panAction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panOpLayout.setVerticalGroup(
            panOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panOpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(234, Short.MAX_VALUE))
        );

        panGuia.addTab("Operações", panOp);

        panDados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botCancelar.setText("Cancelar");
        botCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCancelarActionPerformed(evt);
            }
        });
        panDados.add(botCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 470, 93, 37));

        Salvar.setText("salvar");
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });
        panDados.add(Salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 470, 90, 37));
        panDados.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 840, 20));

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listItemVenda, tabProduto);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${valor}"));
        columnBinding.setColumnName("Valor");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${quant}"));
        columnBinding.setColumnName("Quant");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${produto.descricao}"));
        columnBinding.setColumnName("Produto");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane2.setViewportView(tabProduto);

        panDados.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 800, 190));

        panProduto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Produto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        labValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labValor.setText("Valor ");

        labProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labProduto.setText("Produto");

        labEstoque.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labEstoque.setText("Estoque");

        txtDescricao.setEditable(false);

        botDialog.setText("Selecionar");
        botDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botDialogActionPerformed(evt);
            }
        });

        botAdicionarProd.setText("Adicionar");
        botAdicionarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAdicionarProdActionPerformed(evt);
            }
        });

        botExcluirProd.setText("Excluir");
        botExcluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botExcluirProdActionPerformed(evt);
            }
        });

        labQuantidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labQuantidade.setText("Quantidade");

        txtValorProduto.setEditable(false);

        txtEstoque.setEditable(false);

        txtQuant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panProdutoLayout = new javax.swing.GroupLayout(panProduto);
        panProduto.setLayout(panProdutoLayout);
        panProdutoLayout.setHorizontalGroup(
            panProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panProdutoLayout.createSequentialGroup()
                        .addGroup(panProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labEstoque)
                            .addComponent(labProduto)
                            .addComponent(labValor))
                        .addGroup(panProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panProdutoLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(txtValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panProdutoLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(panProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panProdutoLayout.createSequentialGroup()
                                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(botDialog)))
                                .addContainerGap(45, Short.MAX_VALUE))))
                    .addGroup(panProdutoLayout.createSequentialGroup()
                        .addComponent(labQuantidade)
                        .addGap(18, 18, 18)
                        .addComponent(txtQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(panProdutoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botExcluirProd)
                .addGap(18, 18, 18)
                .addComponent(botAdicionarProd)
                .addContainerGap())
        );
        panProdutoLayout.setVerticalGroup(
            panProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labProduto)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botDialog))
                .addGap(13, 13, 13)
                .addGroup(panProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labEstoque)
                    .addComponent(txtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labValor)
                    .addComponent(txtValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labQuantidade)
                    .addComponent(txtQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botAdicionarProd)
                    .addComponent(botExcluirProd))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        panDados.add(panProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 470, 240));

        panVenda.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Venda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        txtCodVenda.setEditable(false);
        txtCodVenda.setBackground(new java.awt.Color(255, 255, 255));

        labCondigoVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labCondigoVenda.setText("Codigo Venda");

        labDesconto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labDesconto.setText("Desconto");

        txtValor.setEditable(false);

        labValorVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labValorVenda.setText("Valor");

        labValorVenda1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labValorVenda1.setText("Data");

        javax.swing.GroupLayout panVendaLayout = new javax.swing.GroupLayout(panVenda);
        panVenda.setLayout(panVendaLayout);
        panVendaLayout.setHorizontalGroup(
            panVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labCondigoVenda)
                    .addComponent(labDesconto)
                    .addComponent(labValorVenda)
                    .addComponent(labValorVenda1))
                .addGap(25, 25, 25)
                .addGroup(panVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtValor, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addComponent(txtDesconto, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addComponent(txtCodVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                    .addComponent(Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panVendaLayout.setVerticalGroup(
            panVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labCondigoVenda)
                    .addComponent(txtCodVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labDesconto)
                    .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labValorVenda1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        panDados.add(panVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, 190));

        panGuia.addTab("Dados", panDados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panGuia)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panGuia)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botNovoActionPerformed

        listItemVenda.clear();

        txtValor.setText("");

        txtDesconto.setText("");

        panGuia.setEnabledAt(1, true);
        panGuia.setSelectedIndex(1);
        panGuia.setEnabledAt(0, false);
        this.novo = true;
    }//GEN-LAST:event_botNovoActionPerformed

    private void botAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAlterarActionPerformed
        Venda vendaSelecionado;

        int position = tabVenda.getSelectedRow();

        if (position == -1) {
            JOptionPane.showMessageDialog(this, "Selecione a venda na tabela.", "Erro em alterar!", 1);
        } else {
            vendaSelecionado = vendaList.get(position);

            panGuia.setEnabledAt(1, true);
            panGuia.setSelectedIndex(1);
            panGuia.setEnabledAt(0, false);

            txtValor.setValue(vendaSelecionado.getValor());
            txtDesconto.setValue(vendaSelecionado.getDesconto());
            listItemVenda.clear();
            /*           for (ItemVenda iv : vendaSelecionado.getItemVendaList()) {
                listItemVenda.add(iv.getCodProduto());
            }
             */
            alterarC = vendaSelecionado.getCodVenda();
            this.novo = false;
        }
        //na hroa de pegar o ccliente de celular colocar celularselecionado celular.getCliente.getnome
    }//GEN-LAST:event_botAlterarActionPerformed

    private void botExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botExcluirActionPerformed
        Venda VendaExcluir;

        int posicao = tabVenda.getSelectedRow();

        if (posicao == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma venda  na tabela.",
                    "Erro na exclusão!", 0);
        } else {
            VendaExcluir = (Venda) vendaList.get(posicao);

            int resposta = JOptionPane.showConfirmDialog(this,
                    "Deseja exluir a venda? \"" + VendaExcluir.getCodVenda() + "\"?",
                    "Exclusão de Servico", JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION) {
                try {
                    controle.destroy(VendaExcluir.getCodVenda());
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "erro na exclusao");
                }
                vendaList.clear();
            }
        }
    }//GEN-LAST:event_botExcluirActionPerformed

    private void botSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_botSairActionPerformed

    private void botPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botPesquisarActionPerformed
        vendaList.clear();
        vendaList.add(controle.findVenda(Integer.valueOf(txtPesquisa.getText())));
    }//GEN-LAST:event_botPesquisarActionPerformed

    private void botCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCancelarActionPerformed
        panGuia.setEnabledAt(0, true);

        // seleciona a aba a ser apresentada (operações)
        panGuia.setSelectedIndex(0);

        // desabilita a aba de operações
        panGuia.setEnabledAt(1, false);

    }//GEN-LAST:event_botCancelarActionPerformed

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
        Venda venda = new Venda();

        venda.setDesconto(0.0);
        venda.setValor(0.0);
        venda.setDataVenda(Data.getDate());

        for (ItemVenda p : listItemVenda) {
            p.setVenda(venda);
        }

        venda.setItemVendaList(listItemVenda);

        if (this.novo) {
            controle.create(venda);
        } else {
            venda.setCodVenda(alterarC);
            try {
                controle.edit(venda);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "erro na exclusao");
            }
        }

        panGuia.setEnabledAt(0, true);
        panGuia.setSelectedIndex(0);
        panGuia.setEnabledAt(1, false);
        vendaList.clear();
        vendaList.addAll(controle.findVendaEntities());
//dar um return para atualizar a lista 

    }//GEN-LAST:event_SalvarActionPerformed

    private void botDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botDialogActionPerformed
        dialogItemVenda d = new dialogItemVenda(null, true);
        d.setVisible(true);

//        cliente.setCpf(txtCPF.getText());
        prodSelecionado = d.getProd();

        txtDescricao.setText(prodSelecionado.getDescricao());
        txtValorProduto.setValue(prodSelecionado.getValor());
        txtEstoque.setValue(prodSelecionado.getQuant());

//         txtQuant.setValue(());

    }//GEN-LAST:event_botDialogActionPerformed

    private void botExcluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botExcluirProdActionPerformed
        int linha;

        // pega a linha selecionada
        linha = tabProduto.getSelectedRow();

        // não foi selecionado na tabela
        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione o serviço a ser excluído.");
        } else {
            // remove da lista
            listItemVenda.remove(linha);
        }
    }//GEN-LAST:event_botExcluirProdActionPerformed

    private void botAdicionarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAdicionarProdActionPerformed
        //adicionar list items 
        //mandar pra lista          
        ItemVenda novoitem;
        novoitem = new ItemVenda();

        novoitem.setValor(((Number) txtValorProduto.getValue()).doubleValue());
        novoitem.setQuant(Integer.parseInt(txtQuant.getText()));
        novoitem.setProduto(prodSelecionado);

        // adiciona o item na lista
        listItemVenda.add(novoitem);

    }//GEN-LAST:event_botAdicionarProdActionPerformed

    private void txtQuantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Data;
    private javax.persistence.EntityManager Luan_ProjetoPUEntityManager;
    private javax.swing.JButton Salvar;
    private javax.swing.JButton botAdicionarProd;
    private javax.swing.JButton botAlterar;
    private javax.swing.JButton botCancelar;
    private javax.swing.JButton botDialog;
    private javax.swing.JButton botExcluir;
    private javax.swing.JButton botExcluirProd;
    private javax.swing.JButton botNovo;
    private javax.swing.JButton botPesquisar;
    private javax.swing.JButton botSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labCondigoVenda;
    private javax.swing.JLabel labDesconto;
    private javax.swing.JLabel labEstoque;
    private javax.swing.JLabel labProduto;
    private javax.swing.JLabel labQuantidade;
    private javax.swing.JLabel labValor;
    private javax.swing.JLabel labValorVenda;
    private javax.swing.JLabel labValorVenda1;
    private java.util.List<ItemVenda> listItemVenda;
    private javax.swing.JPanel panAction;
    private javax.swing.JPanel panDados;
    private javax.swing.JTabbedPane panGuia;
    private javax.swing.JPanel panOp;
    private javax.swing.JPanel panProduto;
    private javax.swing.JPanel panVenda;
    private javax.swing.JTable tabProduto;
    private javax.swing.JTable tabVenda;
    private javax.swing.JTextField txtCodVenda;
    private javax.swing.JFormattedTextField txtDesconto;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JFormattedTextField txtEstoque;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JFormattedTextField txtQuant;
    private javax.swing.JFormattedTextField txtValor;
    private javax.swing.JFormattedTextField txtValorProduto;
    private java.util.List<modelo.Venda> vendaList;
    private javax.persistence.Query vendaQuery;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
