/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ControlaCliente;
import Controle.exceptions.NonexistentEntityException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Cliente;

/**
 *
 * @author aluno
 */
public class TelaCliente extends javax.swing.JInternalFrame {
    boolean novo;
    int mouseX, mouseY;
    int alterarC;
    ControlaCliente controle = new ControlaCliente(Entidades.GerenciamentoEntidades.getFabEntidades());
    
    
    /**
     * Creates new form TelaCadastroCliente
     */
    public TelaCliente() {
        initComponents();
        panGuia.setEnabledAt(0, true);
        panGuia.setEnabledAt(1, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        Luan_ProjetoPUEntityManager0 = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("Luan_ProjetoPU").createEntityManager();
        clienteQuery = java.beans.Beans.isDesignTime() ? null : Luan_ProjetoPUEntityManager0.createQuery("SELECT c FROM Cliente c");
        listaClientes = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(clienteQuery.getResultList());
        panGuia = new javax.swing.JTabbedPane();
        panOp = new javax.swing.JPanel();
        panAction = new javax.swing.JPanel();
        botNovo = new javax.swing.JButton();
        botAlterar = new javax.swing.JButton();
        botExcluir = new javax.swing.JButton();
        botSair = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabCliente = new javax.swing.JTable();
        botPesquisar = new javax.swing.JButton();
        panDados = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JFormattedTextField();
        jSeparator2 = new javax.swing.JSeparator();
        botCancelar = new javax.swing.JButton();
        botSalvar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCEP = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JComboBox<>();

        setClosable(true);
        setVisible(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        panGuia.setName("Cliente"); // NOI18N
        panGuia.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panGuiaMouseDragged(evt);
            }
        });
        panGuia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panGuiaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panGuiaMouseReleased(evt);
            }
        });

        panAction.setBorder(javax.swing.BorderFactory.createTitledBorder("Ações"));
        panAction.setLayout(new java.awt.GridLayout(1, 0));

        botNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/Imagens/Adicionar usuário masculino-30.png"))); // NOI18N
        botNovo.setText("Novo");
        botNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botNovoActionPerformed(evt);
            }
        });
        panAction.add(botNovo);

        botAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/Imagens/Editar-30.png"))); // NOI18N
        botAlterar.setText("Alterar");
        botAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAlterarActionPerformed(evt);
            }
        });
        panAction.add(botAlterar);

        botExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/Imagens/Excluir-30.png"))); // NOI18N
        botExcluir.setText("Excluir");
        botExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botExcluirActionPerformed(evt);
            }
        });
        panAction.add(botExcluir);

        botSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/Imagens/Porta aberta-30.png"))); // NOI18N
        botSair.setText("Sair");
        botSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botSairActionPerformed(evt);
            }
        });
        panAction.add(botSair);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta de clientes"));

        jLabel1.setText("Nome");

        txtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaActionPerformed(evt);
            }
        });

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listaClientes, tabCliente);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codCliente}"));
        columnBinding.setColumnName("Cod Cliente");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nome}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${telefone}"));
        columnBinding.setColumnName("Telefone");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${endereco}"));
        columnBinding.setColumnName("Endereco");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(tabCliente);

        botPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/Imagens/Pesquisar-15.png"))); // NOI18N
        botPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(botPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panOpLayout = new javax.swing.GroupLayout(panOp);
        panOp.setLayout(panOpLayout);
        panOpLayout.setHorizontalGroup(
            panOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panOpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panAction, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE))
                .addContainerGap())
        );
        panOpLayout.setVerticalGroup(
            panOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panOpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        panGuia.addTab("Operações", panOp);

        panDados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Nome");
        panDados.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 37, -1, -1));
        panDados.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 414, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Endereço");
        panDados.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));
        panDados.add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 414, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Telefone");
        panDados.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelefoneKeyPressed(evt);
            }
        });
        panDados.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 193, -1));
        panDados.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 477, 788, 10));

        botCancelar.setText("Cancelar");
        botCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCancelarActionPerformed(evt);
            }
        });
        panDados.add(botCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 490, 93, 37));

        botSalvar.setText("Salvar");
        botSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botSalvarActionPerformed(evt);
            }
        });
        panDados.add(botSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 490, 90, 37));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("CPF");
        panDados.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));
        panDados.add(txtCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 271, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("CEP");
        panDados.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));
        panDados.add(txtCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 270, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Cidade");
        panDados.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));
        panDados.add(txtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 270, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Estado");
        panDados.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        txtEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        txtEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoActionPerformed(evt);
            }
        });
        panDados.add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 120, -1));

        panGuia.addTab("Dados", panDados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panGuia)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panGuia)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botNovoActionPerformed
       
        txtEndereco.setText("");
        
        txtNome.setText("");
        
        txtTelefone.setText("");
        
        txtCEP.setText("");
        
        txtEstado.setSelectedIndex(0);
        
        txtCPF.setText("");
        
        txtCidade.setText("");
        
        panGuia.setEnabledAt(1, true);
        
        panGuia.setSelectedIndex(1);
        
        panGuia.setEnabledAt(0, false);
        
        this.novo = true;
    }//GEN-LAST:event_botNovoActionPerformed

    private void botAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAlterarActionPerformed
        Cliente clienteSelecionado;

        int position = tabCliente.getSelectedRow();

        if (position == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um cliente na tabela.", "Erro em alterar!", 1);
        } else {
            clienteSelecionado = listaClientes.get(position);
            panGuia.setEnabledAt(1, true);
            panGuia.setSelectedIndex(1);
            panGuia.setEnabledAt(0, false);
            txtEndereco.setText(clienteSelecionado.getEndereco());
            txtNome.setText(clienteSelecionado.getNome());
            txtTelefone.setText(clienteSelecionado.getTelefone());
            txtCPF.setText(clienteSelecionado.getCpf());
            txtCidade.setText(clienteSelecionado.getCidade());
            txtEstado.setSelectedItem(clienteSelecionado.getEstado());
            txtCEP.setText(clienteSelecionado.getCep());
            alterarC = clienteSelecionado.getCodCliente();
            this.novo = false;
        }
    }//GEN-LAST:event_botAlterarActionPerformed

    private void botExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botExcluirActionPerformed
        Cliente clienteExcluir;
        int posicao = tabCliente.getSelectedRow();

        if (posicao == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um cliente na tabela.",
                "Erro na exclusão!", 0);
        } else {
            clienteExcluir = listaClientes.get(posicao);

            int resposta = JOptionPane.showConfirmDialog(this,
                "Deseja exluir o Cliente \"" + clienteExcluir.getNome() + "\"?",
                "Exclusão de cliente", JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION) {
                try {
                    controle.destroy(clienteExcluir.getCodCliente());
                } catch (NonexistentEntityException ex) {
                    Logger.getLogger(TelaCliente.class.getName()).log(Level.SEVERE, null, ex);
                }
                listaClientes.clear();
                listaClientes.addAll(controle.findClienteEntities());
            }
        }
    }//GEN-LAST:event_botExcluirActionPerformed

    private void botSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_botSairActionPerformed

    private void botPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botPesquisarActionPerformed

        listaClientes.clear();
        listaClientes.addAll(controle.schNomeCliente(txtPesquisa.getText()));
        
    }//GEN-LAST:event_botPesquisarActionPerformed

    private void txtTelefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefoneKeyPressed
        if (txtTelefone.getHeight() == 13 && (evt.getKeyCode() != java.awt.event.KeyEvent.VK_DELETE || evt.getKeyCode() != java.awt.event.KeyEvent.VK_BACK_SPACE)) {

            try {
                txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
            } catch (java.text.ParseException ex) {
                ex.printStackTrace();
            }

        }
        if (txtTelefone.getHeight() == 14 && (evt.getKeyCode() == java.awt.event.KeyEvent.VK_DELETE || evt.getKeyCode() == java.awt.event.KeyEvent.VK_BACK_SPACE)) {
            try {
                txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
            } catch (java.text.ParseException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_txtTelefoneKeyPressed

    private void botCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCancelarActionPerformed
        panGuia.setEnabledAt(0, true);

        // seleciona a aba a ser apresentada (operações)
        panGuia.setSelectedIndex(0);

        // desabilita a aba de operações
        panGuia.setEnabledAt(1, false);
    }//GEN-LAST:event_botCancelarActionPerformed

    private void botSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botSalvarActionPerformed
        Cliente cliente = new Cliente();

        cliente.setNome(txtNome.getText());
        cliente.setEndereco(txtEndereco.getText());
        cliente.setTelefone(txtTelefone.getText());   
        cliente.setCpf(txtCPF.getText());
        cliente.setCep(txtCEP.getText());
        cliente.setEstado(txtEstado.getSelectedItem().toString());
        cliente.setCidade(txtCidade.getText());
        
        if (this.novo) {
            controle.create(cliente);
        } else {
            cliente.setCodCliente(alterarC);
            try {
                controle.edit(cliente);
            } catch (Exception ex) {
                Logger.getLogger(TelaCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        panGuia.setEnabledAt(0, true);
        panGuia.setSelectedIndex(0);
        panGuia.setEnabledAt(1, false);
        listaClientes.clear();
        listaClientes.addAll(controle.findClienteEntities());
    }//GEN-LAST:event_botSalvarActionPerformed

    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        
    }//GEN-LAST:event_formMouseDragged

    private void panGuiaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panGuiaMousePressed
       
    }//GEN-LAST:event_panGuiaMousePressed

    private void panGuiaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panGuiaMouseDragged
      
    }//GEN-LAST:event_panGuiaMouseDragged

    private void panGuiaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panGuiaMouseReleased

    }//GEN-LAST:event_panGuiaMouseReleased

    private void txtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager Luan_ProjetoPUEntityManager0;
    private javax.swing.JButton botAlterar;
    private javax.swing.JButton botCancelar;
    private javax.swing.JButton botExcluir;
    private javax.swing.JButton botNovo;
    private javax.swing.JButton botPesquisar;
    private javax.swing.JButton botSair;
    private javax.swing.JButton botSalvar;
    private javax.persistence.Query clienteQuery;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private java.util.List<modelo.Cliente> listaClientes;
    private javax.swing.JPanel panAction;
    private javax.swing.JPanel panDados;
    private javax.swing.JTabbedPane panGuia;
    private javax.swing.JPanel panOp;
    private javax.swing.JTable tabCliente;
    private javax.swing.JTextField txtCEP;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JComboBox<String> txtEstado;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JFormattedTextField txtTelefone;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
